### ISSUE TITLE
Request to add TunnlTo

### ISSUE THREAD

**Issue by brendanosborne** [cedrickchee/awesome-wireguard#11]
Hi,

I would like to add a link.

**REPO**:
https://github.com/TunnlTo/desktop-app

**DESCRIPTION**:
TunnlTo is a lightweight, fast, Windows WireGuard VPN client built for split tunneling.

**AUTHOR**:
https://github.com/brendanosborne

**Comment by cedrickchee** [comment]
Thank you for your contribution.
