### ISSUE TITLE
Add wireguard-ui

### ISSUE THREAD

**Issue by cedrickchee** [cedrickchee/awesome-wireguard#25]
I would like to add a link.

**REPO**: https://github.com/ngoduykhanh/wireguard-ui

**DESCRIPTION**: A web user interface to manage your WireGuard setup.

**AUTHOR**: ngoduykhanh

**Comment by DevSH01** [comment]
Please merge this https://github.com/cedrickchee/awesome-wireguard/pull/19

**Comment by cedrickchee** [comment]
Today, I will take the chance to start going through all the issues and pending PRs.

**Comment by cedrickchee** [comment]
@DevSH01 I will review your PR now. Thank you for giving me an extra hand. The hero 😄
