### ISSUE TITLE
Status of seashell/drago

### ISSUE THREAD

**Issue by svenwanzenried** [cedrickchee/awesome-wireguard#3]
Hi,
I would like to turn your attention to your link [seashell/drago](https://github.com/seashell/drago)
It seems to be inactive since quite some time ( maybe add a note next to the reference? )
Kind regards, Sven

**Comment by cedrickchee** [comment]
Hi Sven,
Apologize for the super late response and necroposting.
Thank you for bringing this to my attention.

> It seems to be inactive since quite some time ( maybe add a note next to the reference? )

I have checked Drago. There's an open Issue where people asking the status of that project: https://github.com/seashell/drago/issues/84

TBH, I don't know and cannot confirm the status of that project.
Anyway, I will add a note next to Drago link as you suggest.

Thank you.

Rgds,
Cedric

**Comment by cedrickchee** [comment]
Done!
